project:
  type: website
  output-dir: docs

website:
  title: "Evan Atchison"
  navbar:
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - sidebar:mini_project1
      - sidebar:mini_project2
      - sidebar:about
      
  sidebar:
    - id: mini_project1
      title: "State Mapping"
      contents:
        - chloropleth_map.qmd
        - Wisconsin.qmd
    - id: about
      title: "About Me"
      contents: 
        - about.qmd
    - id: mini_project2
      title: "Null Hypothesis Test"
      contents:
        - null_hypothesis.qmd
      
  page-footer:
      left: |
        &copy; Evan Atchison, 2024<br>
        All content licensed under <i class='bi-badge-cc'></i>        [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      right: |
        Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

