---
title: "About"
sidebar: true
format:
  html: default
editor_options:
  chunk_output_type: console
---

## Introduction

I am a sophomore B.A. History Major at St. Olaf College in Northfield, Minnesota. While you might think to yourself, "A history major who has a coding webpage? How odd!", I also have a love for coding and am pursuing a Concentration in Statistics and Data Science alongside my History major. I hope to combine my two interests of history and data science to tell historical stories using data. Outside of my studies, I am a percussionist in both the St. Olaf Band and St. Olaf Orchetra.

### Interests

I am a passionate sports fan and I hope to translate this passion into the work I do on this website. While primarily a soccer fanatic, I also have great interest in basketball and football analytics. Using this passion, I love creating models that not only allow sports fans and executives to reflect on what has created sporting success in the past, but also what is predicted for the future of sports. Influenced by my love of history, I am also interested in political and population data that tells the stories of human migrations and changes in global political landscapes. 

#### Contact

Want to reach out? Feel free to connect with me by **email** <a href='mailto:atchis1@stolaf.edu'>atchis1\@stolaf.edu</a>